【Model】Users 作成
du-cis-mil/AccountantSystem pull request #3
Opened 2018-07-12 15:07 UTC by AyanoIkegami

2018-07-12 20:21 UTC, xkazuma commented on src/Controller/UsersController.php
> +  function index()
関数名から処理内容をある程度把握できるように工夫してください．
この処理の場合なら getAll() でしょうか．

2018-07-12 20:22 UTC, xkazuma commented on src/Controller/UsersController.php
> +    // $id = $this->request->query['id'];
不要なコードは排除しましょう，逆に何をするステートメントなのかについてコメントしておくべきです．
ただ，以降のような単純なコードの場合は不要です

2018-07-12 20:29 UTC, xkazuma commented on src/SQL/users.sql
> +  created DATE,
Datetime 型にしましょう．

created datetime DEFAULT NULL,

2018-07-12 20:29 UTC, xkazuma commented on src/SQL/users.sql
> +  updated DATE
modified も Datetime 型にしましょう．

modified datetime DEFAULT NULL,

2018-07-13 06:41 UTC, AyanoIkegami commented on src/Controller/UsersController.php
> +  function index()
承知いたしました。
ただ、関数名とctpファイル名が連携しているため、動詞で関数名を決めるとctpの命名が不自然になると思います。
なお、ctpファイル名はURLで指定する時に用います。(この場合、localhost/AccountantSystem/getAllになります)
なので、IndexからAllUser等に命名し直した方が良いと考えておりますがどちらが宜しいでしょうか。

2018-07-13 08:48 UTC, xkazuma commented on src/Controller/UsersController.php
> +  function index()
あーそう言うのありましたね．
そういうことであれば getAll() 関数は定義せずにそのままで良いです．

2018-07-13 08:51 UTC, xkazuma commented on src/Template/Users/index.ctp
> +  <thead><tr>
コードは見やすく．
```
<thead>
    <tr>
        <th>id</th>
        <th>name</th>
        <th>mail</th>
        <th>age</th>
    </tr>
</thead>
```

2018-07-13 08:53 UTC, xkazuma requested changes

2018-07-13 08:53 UTC, xkazuma commented on src/Template/Users/index.ctp
> +  <?php foreach ($data->toArray() as $obj): ?>
以降のインデントが狂っている？

2018-07-13 10:07 UTC, xkazuma commented
基本オッケーですが，他のみんなが AccountantSystem をアクセスできるようにしてからマージしたいと思います．それまで，このリクエストは放置しておきますが，次のモデルも続けて作ってください．

2018-07-13 10:27 UTC, closed without merging